<?php

/**
 * @file
 * Contains localgov_subsites_extras.module.
 */

declare(strict_types=1);

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_node().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_html(&$variables) {

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteService $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $theme = $subSiteService->getCurrentSubsiteTheme();
  if ($theme) {
    $variables['attributes']['class'][] = 'subsite-extra';
    $variables['attributes']['class'][] = 'subsite-extra--color-' . $theme;
  }
}

/**
 * Implements hook_preprocess_menu().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_menu(&$variables) {

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteService $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $subsiteHomePage = $subSiteService->getHomePage();
  if ($subsiteHomePage) {
    $variables['subsite_homepage_link'] = $subsiteHomePage->toLink();
  }
}

/**
 * Implements hook_entity_bundle_create().
 *
 * When a new content type is created, this adds the subsite menu to its
 * available menus.
 */
function localgov_subsites_extras_entity_bundle_create($entity_type_id, $bundle) {

  if ($entity_type_id !== 'node') {
    return;
  }

  /** @var \Drupal\Node\NodeTypeInterface $type */
  $type = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->load($bundle);

  if ($type) {
    $availableMenus = $type->getThirdPartySetting('menu_ui', 'available_menus', ['main']);
    $availableMenus[] = 'subsites';
    $type->setThirdPartySetting('menu_ui', 'available_menus', $availableMenus);
    $type->save();
  }
}

// phpcs:disable

// Ideally, we want this hook in localgov_directories.
// Wrap it for now so we can move it there cleanly.
if (!function_exists('localgov_directories_subsites_extra_current_node_alter')) {
  /**
   * Implements hook_subsites_extra_current_node_alter().
   */
  function localgov_directories_subsites_extra_current_node_alter(?NodeInterface &$node) {
    if ($node instanceof NodeInterface && $node->hasField('localgov_directory_channels')) {
      $directoryChannel = $node->localgov_directory_channels->entity;
      if ($directoryChannel instanceof NodeInterface) {
        $node = $directoryChannel;
      }
    }
  }
}

// Ideally, we want this hook in localgov_guides.
// Wrap it for now so we can move it there cleanly.
if (!function_exists('localgov_guides_subsites_extra_current_node_alter')) {
  /**
   * Implements hook_subsites_extra_current_node_alter().
   */
  function localgov_guides_subsites_extra_current_node_alter(?NodeInterface &$node) {
    if ($node instanceof NodeInterface && $node->hasField('localgov_guides_parent')) {
      $guideParent = $node->localgov_guides_parent->entity;
      if ($guideParent instanceof NodeInterface) {
        $node = $guideParent;
      }
    }
  }
}

// phpcs:enable
