<?php

/**
 * Implements hook_install().
 */
function localgov_subsites_extras_install() {

  // Add the 'subsites' menu included in this module's config to the existing
  // content types.

  /** @var \Drupal\Node\NodeTypeInterface[] $types */
  $types = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->loadMultiple();

  foreach ($types as $type) {
    $availableMenus = $type->getThirdPartySetting('menu_ui', 'available_menus', ['main']);
    $availableMenus[] = 'subsites';
    $type->setThirdPartySetting('menu_ui', 'available_menus', $availableMenus);
    $type->save();
  }

}
