<?php

/**
 * @file
 * Contains localgov_subsites_extras.module.
 */

declare(strict_types=1);

use Drupal\node\NodeInterface;

/**
 * Implements hook_preprocess_node().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_html(&$variables) {

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteServiceInterface $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $theme = $subSiteService->getCurrentSubsiteTheme();
  if ($theme) {
    $variables['attributes']['class'][] = 'subsite-extra';
    $variables['attributes']['class'][] = 'subsite-extra--color-' . $theme;
  }
}

/**
 * Implements hook_preprocess_menu().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_menu(&$variables) {

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteServiceInterface $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $subsiteHomePage = $subSiteService->getHomePage();
  if ($subsiteHomePage) {
    $variables['subsite_homepage_link'] = $subsiteHomePage->toLink();
  }
}

/**
 * Implements hook_entity_bundle_create().
 *
 * When a new content type is created, this adds the subsite menu to its
 * available menus.
 */
function localgov_subsites_extras_entity_bundle_create($entity_type_id, $bundle) {

  if ($entity_type_id !== 'node') {
    return;
  }

  /** @var \Drupal\Node\NodeTypeInterface $type */
  $type = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->load($bundle);

  if ($type) {
    $availableMenus = $type->getThirdPartySetting('menu_ui', 'available_menus', ['main']);
    $availableMenus[] = 'subsites';
    $type->setThirdPartySetting('menu_ui', 'available_menus', $availableMenus);
    $type->save();
  }

}

/**
 * Implements hook_pathauto_alias_alter().
 *
 * Prepends Subsite homepage path alias to child page path aliases.
 *
 * @todo Automated tests.
 */
function localgov_subsites_extras_pathauto_alias_alter(&$alias, array &$context) {

  if ($context['module'] !== 'node') {
    return;
  }

  $src_node = $context['data']['node'];

  $subsite_home = Drupal::service('localgov_subsites_extras.service')->getHomePage($src_node);
  if (!$subsite_home instanceof NodeInterface) {
    return;
  }

  $is_child_page = $subsite_home->id() !== $src_node->id();
  if (!$is_child_page) {
    return;
  }

  $subsite_home_path = $subsite_home->toUrl()->toString();
  $has_subsite_alias_prefix = str_starts_with($alias, $subsite_home_path);
  if ($has_subsite_alias_prefix) {
    return;
  }

  $alias = $subsite_home_path . $alias;
}
