<?php

/**
 * @file
 * Contains localgov_subsites_extras.module.
 */

declare(strict_types=1);

/**
 * Implements hook_preprocess_node().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_html(&$variables) {

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteService $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $theme = $subSiteService->getCurrentSubsiteTheme();
  if ($theme) {
    $variables['attributes']['class'][] = 'subsite';
    $variables['attributes']['class'][] = 'color--' . $theme;
  }
}

/**
 * Implements hook_preprocess_page().
 *
 * When a node is a child menu item of a subsite homepage node, this finds the
 * subsite homepage and inserts some of its properties into the template.
 */
function localgov_subsites_extras_preprocess_menu(&$variables) {

  if ($variables['menu_name'] !== 'main') {
    return;
  }

  /** @var \Drupal\localgov_subsites_extras\Service\SubsiteService $subSiteService */
  $subSiteService = \Drupal::service('localgov_subsites_extras.service');

  // If the current node is part of a subsite, $subsiteHomePage will be the
  // subsite's homepage node. If it's not, it'll be null.
  $subsiteHomePage = $subSiteService->getHomePage();
  if ($subsiteHomePage) {
    $variables['subsite_homepage_link'] = $subsiteHomePage->toLink();
  }
}

/**
 * Implements hook_entity_bundle_create().
 *
 * When a new content type is created, this adds the subsite menu to its
 * available menus.
 */
function localgov_subsites_extras_entity_bundle_create($entity_type_id, $bundle) {

  if ($entity_type_id !== 'node') {
    return;
  }

  /** @var \Drupal\Node\NodeTypeInterface $types */
  $type = \Drupal::entityTypeManager()
    ->getStorage('node_type')
    ->load($bundle);

  if ($type) {
    $availableMenus = $type->getThirdPartySetting('menu_ui', 'available_menus', ['main']);
    $availableMenus[] = 'subsites';
    $type->setThirdPartySetting('menu_ui', 'available_menus', $availableMenus);
    $type->save();
  }

}
